using System;

namespace PearXLib
{
    /// <summary>
    /// PearXLib random utilities.
    /// </summary>
    public class RandomUtils
    {
        /// <summary>
        /// Generates random character.
        /// </summary>
        /// <returns>Random character.</returns>
        public static char GenChar(Random rand)
        {
            const string chars = "abcdefghijklmnopqrstuvwxyz";
            int i = rand.Next(chars.Length);
            return chars[i];
        }

        /// <summary>
        /// Generates random digit.
        /// </summary>
        /// <returns>Random digit</returns>
        public static int GenNumber(Random rand)
        {
            return rand.Next(0, 10);
        }

        /// <summary>
        /// Generate random number.
        /// </summary>
        /// <param name="min">Minimal random number (inclusive).</param>
        /// <param name="max">Maximal random number (inclusive).</param>
        /// <param name="rand">Your random.</param>
        /// <returns>Random number.</returns>
        public static int GenNumber(Random rand, int min, int max)
        {
            return rand.Next(min, max + 1);
        }

        /// <summary>
        /// Generates random symbol.
        /// </summary>
        /// <param name="rand"></param>
        /// <returns></returns>
        public static char GenSymbol(Random rand)
        {
            int i = rand.Next(0, 26);
            switch (i)
            {
                case 0:
                    return '!';
                case 1:
                    return '@';
                case 2:
                    return '"';
                case 3:
                    return '#';
                case 4:
                    return '№';
                case 5:
                    return '$';
                case 6:
                    return ';';
                case 7:
                    return '%';
                case 8:
                    return '^';
                case 9:
                    return ':';
                case 10:
                    return '&';
                case 11:
                    return '?';
                case 12:
                    return '*';
                case 13:
                    return '(';
                case 14:
                    return ')';
                case 15:
                    return '-';
                case 16:
                    return '_';
                case 17:
                    return '+';
                case 18:
                    return '=';
                case 19:
                    return '\\';
                case 20:
                    return '|';
                case 21:
                    return '/';
                case 22:
                    return '\'';
                case 23:
                    return '~';
                case 24:
                    return '.';
                case 25:
                    return ',';
                default:
                    return '!';
            }
        }

        /// <summary>
        /// Generates random number/char/symbol.
        /// </summary>
        /// <returns>Random.</returns>
        public static char GenRandom(Random rand, bool useSymbols)
        {
            int i;
            if (useSymbols)
                i = rand.Next(0, 4);
            else
                i = rand.Next(0, 3);
            switch (i)
            {
                case 0:
                    return Convert.ToChar(GenNumber(rand).ToString());
                case 1:
                    return GenChar(rand);
                case 2:
                    return Convert.ToChar(GenChar(rand).ToString().ToUpper());
                case 3:
                    return GenSymbol(rand);
                default:
                    return '0';
            }

        }

        /// <summary>
        /// <![CDATA[Generates a random string by a template.
        /// Template usage:
        /// %num% - a random figure, ex. 6 or 7.
        /// %char% - a random character, ex. b or e.
        /// %CHAR% - a random character in uppercase, ex. Z or H.
        /// %sym% - a random symbol, ex. ~ or &.
        /// %rand% - a random symbol, character, or figure.
        /// %randws% - a random character or figure.
        /// Example template: TEST%rand%%sym%%CHAR%%CHAR%_HEHE. Example return: TEST&*FE_HEHE]]>
        /// </summary>
        /// <param name="template">A template</param>
        /// <param name="rand">Your random</param>
        /// <returns>A random generated by template string.</returns>
        public static string ByTemplate(string template, Random rand)
        {
            while (template.Contains("%char%"))
            {
                template = PXL.ReplaceFirst(template, "%char%", GenChar(rand).ToString());
            }
            while (template.Contains("%CHAR%"))
            {
                template = PXL.ReplaceFirst(template, "%CHAR%", GenChar(rand).ToString().ToUpper());
            }
            while (template.Contains("%num%"))
            {
                template = PXL.ReplaceFirst(template, "%num%", GenNumber(rand).ToString());
            }
            while (template.Contains("%rand%"))
            {
                template = PXL.ReplaceFirst(template, "%rand%", GenRandom(rand, true).ToString());
            }
            while (template.Contains("%randws%"))
            {
                template = PXL.ReplaceFirst(template, "%randws%", GenRandom(rand, false).ToString());
            }
            while (template.Contains("%sym%"))
            {
                template = PXL.ReplaceFirst(template, "%sym%", GenSymbol(rand).ToString());
            }
            return template;
        }
    }
}
